---
- debug:
    msg:
    - "ansible_distribution = {{ansible_distribution}}"
    - "ansible_distribution_release = {{ansible_distribution_release}}"
    - "ansible_distribution_version= {{ansible_distribution_version}}"

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
