---
- include_tasks: setupRHsubs.yml
  when: initialize_rh_subscriptions

- name: Set EPEL repo facts
  set_fact:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Install base packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - ansible
    - wget
    - git
    - net-tools
    - bind-utils
    - yum-utils
    - bash-completion
    - python-docker-py

- name: install Ansible Dependencies
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python-pip

- name: install jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    dest: /usr/bin/jq
    mode: 0555

#- name: Reboot machine with latest packages
#  reboot:
