---
# load conjur policy, updates variables then starts read loop
- hosts: conjurMaster
  gather_facts: false
  vars:
    conjur_cli_container_name: conjur-cli
    conjur_admin_password: Cyberark1
    read_iterations: 100
  tasks:
  - name: Timestamp
    debug: msg="{{ lookup('pipe','date +%H:%M:%S') }}"

  - name: Copy policy to mounted CLI policy dir 
    copy:
      src: "./policy.yml"
      dest: /tmp/conjur_policies/policy.yml

  - name: Load Conjur policy
    shell: |
      docker exec {{ conjur_cli_container_name }} conjur authn login -u admin -p {{ conjur_admin_password }}
      docker exec {{ conjur_cli_container_name }} conjur policy load root /policy/policy.yml

  - name: Rotate values
    shell: |
      docker exec {{ conjur_cli_container_name }} conjur variable values add secrets/db_username $(openssl rand -hex 12)
      docker exec {{ conjur_cli_container_name }} conjur variable values add secrets/db_password $(openssl rand -hex 12)

  - name: Read values in a loop
    shell: |
      docker exec {{ conjur_cli_container_name }} conjur variable value secrets/db_username
      docker exec {{ conjur_cli_container_name }} conjur variable value secrets/db_password
    until: false
    retries: "{{ read_iterations }}"
    ignore_errors: yes 

  - name: Timestamp
    debug: msg="{{ lookup('pipe','date +%H:%M:%S') }}"
