--- # Tasks for configuring Conjur etc cluster settings for failover

- name: Login as admin
  shell: docker exec conjur-cli conjur authn login -u admin -p {{ conjur_admin_password }}

- name: Load cluster policy
  shell: docker exec conjur-cli conjur policy load root /policy/cluster-policy.yml

- name: Enroll Master in HA cluster
  shell: docker exec {{ conjur_master_container_name }} evoke cluster enroll --cluster-machine-name {{ conjur_master_container_name }} {{ conjur_cluster_name }}
